---
driver:
  name: vsphere
  driver_options:
    host: '172.16.20.2'
    user: 'administrator@vsphere.local'
    password: 'PASSWORD'
    insecure: true
  machine_options:
    start_timeout: 600
    create_timeout: 600
    ready_timeout: 90
    bootstrap_options:
      use_linked_clone: true
      datacenter: 'Datacenter'
      template_name: 'ubuntu16-template'
      template_folder: 'Linux'
      resource_pool: 'Cluster'
      num_cpus: 2
      memory_mb: 4096
      ssh:
        user: admini
        paranoid: false
        password: admini
        port: 22

provisioner:
  name: chef_zero
  sudo_command: sudo

verifier:
  name: inspec

transport:
  username: "admini"
  password: admini

platforms:
  - name: ubuntu-16.04
  - name: windows
    driver:
      machine_options:
        start_timeout: 600
        create_timeout: 600
        ready_timeout: 90
        bootstrap_options:
          use_linked_clone: true
          datacenter: 'Datacenter'
          template_name: 'windows2012R2'
          template_folder: 'Windows'
          resource_pool: 'Cluster'
          num_cpus: 2
          memory_mb: 8096
          ssh:
            user: "administrator"
            paranoid: false
            password: "Admini@"
            port: 5985

suites:
- name: default
  run_list:
  - recipe[my_cookbook::default]
